server:
  port: 8080

spring:
  application:
    name: chamoWishes

  datasource:
    # AutoServer es para conexion simultanea.
    url: jdbc:h2:file:./data/chamoWishes;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  sql:
    init:
      mode: always

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
      # Esto es para que se usen los mismos nombres de variables que yo defino, hp hibernate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format-sql: true

logging:
  level:
    org.springframework: INFO
    com.myapp: DEBUG

jwt:
  secret: chamoWishesSecretKey2024XyZ123456789AbCdEfGhIjKlMnOpQrStUvWxYz
  expiration-ms: 120000